#!/bin/bash

# Stop and remove containers
docker-compose -f docker-compose-production.yml stop <service-name> <service-name> ...
docker-compose -f docker-compose-production.yml rm -f <service-name> <service-name> ...

# Remove images
docker rmi $(docker images | grep -E '<service-name>|<service-name>' | awk '{print $3}') 2>/dev/null || true

# Rebuild and start services
docker compose -f docker-compose-production.yml build --no-cache <service-name> <service-name> ...
docker compose -f docker-compose-production.yml up -d <service-name> <service-name> ...

# Show logs
docker-compose -f docker-compose-production.yml logs -f <service-name> <service-name> ...
